version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 905418053651.dkr.ecr.ap-northeast-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t dev-ecr-01 .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker tag dev-ecr-01:latest 905418053651.dkr.ecr.ap-northeast-1.amazonaws.com/dev-ecr-01:latest
      - docker push 905418053651.dkr.ecr.ap-northeast-1.amazonaws.com/dev-ecr-01:latest
      - printf '[{"name":"%s","imageUri":"%s"}]' dev-ecr-01 905418053651.dkr.ecr.ap-northeast-1.amazonaws.com/dev-ecr-01:latest > imagedefinitions.json

artifacts:
  files: 
    - imagedefinitions.json